{"timestamp":"2025-08-21T15:52:35.619232","level":"info","event":"DAG bundles loaded: dags-folder","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-08-21T15:52:35.619633","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/f1_driver_test_dag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-08-21T15:52:46.128644","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"HTTPError","exc_value":"HTTP Error 504: Gateway Timeout","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":877,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1164,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/decorator.py","lineno":251,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":217,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":240,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/opt/airflow/dags/f1_driver_test_dag.py","lineno":47,"name":"extract_f1_sessions"},{"filename":"/usr/local/lib/python3.12/urllib/request.py","lineno":215,"name":"urlopen"},{"filename":"/usr/local/lib/python3.12/urllib/request.py","lineno":521,"name":"open"},{"filename":"/usr/local/lib/python3.12/urllib/request.py","lineno":630,"name":"http_response"},{"filename":"/usr/local/lib/python3.12/urllib/request.py","lineno":559,"name":"error"},{"filename":"/usr/local/lib/python3.12/urllib/request.py","lineno":492,"name":"_call_chain"},{"filename":"/usr/local/lib/python3.12/urllib/request.py","lineno":639,"name":"http_error_default"}],"is_group":false,"exceptions":[]}]}
